// This file is @generated by Rafx's bindings generator; DO NOT MODIFY
use cmake::Config;

fn main() {
    let dst = Config::new("../../")
        .generator("Ninja")
        .define("RAFX_BUILD_EXAMPLES", "OFF")
        .define("RAFX_D3D12_SUPPORT", "ON")
        .define("CMAKE_MSVC_RUNTIME_LIBRARY", "MultiThreaded$($<$<CONFIG:Debug>:Debug$>)DLL")
        .build();

    println!("cargo:rustc-link-search=native={}/build", dst.display());
    println!("cargo:rustc-link-search=native={}/build/thirdparty/NRI", dst.display());
    println!("cargo:rustc-link-search=native={}/build/thirdparty/NRD", dst.display());
    println!("cargo:rustc-link-search=native={}/build/_deps/shadermake-build", dst.display());
    println!("cargo:rustc-link-search=native={}/build/_deps/slang-src/lib", dst.display());
    println!("cargo:rustc-link-search=native={}/build/_deps/nvapi-src/amd64", dst.display());
    println!("cargo:rustc-link-lib=static=rafx");
    println!("cargo:rustc-link-lib=static=NRI");
    println!("cargo:rustc-link-lib=static=NRI_D3D12");
    println!("cargo:rustc-link-lib=static=NRI_NONE");
    println!("cargo:rustc-link-lib=static=NRI_Shared");
    println!("cargo:rustc-link-lib=static=NRI_Validation");
    println!("cargo:rustc-link-lib=static=NRI_VK");
    println!("cargo:rustc-link-lib=static=NRD");
    println!("cargo:rustc-link-lib=static=ShaderMakeBlob");
    println!("cargo:rustc-link-lib=static=nvapi64");
    println!("cargo:rustc-link-lib=dylib=slang");

    println!("cargo:rustc-link-lib=user32");
    println!("cargo:rustc-link-lib=gdi32");
    println!("cargo:rustc-link-lib=shell32");
    println!("cargo:rustc-link-lib=dxgi");
    println!("cargo:rustc-link-lib=d3d12");
    println!("cargo:rustc-link-lib=dxguid");

    // Ensure we rebuild if the C++ source changes
    println!("cargo:rerun-if-changed=../../src");
    println!("cargo:rerun-if-changed=../../include");
}
